name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Coursier cache
      uses: coursier/cache-action@v5
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run tests
      run: |  
      sbt "test:testOnly ParserTests"
      rm -rf "$HOME/.ivy2/local" || true
      find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
      find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
      find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
      find $HOME/.sbt                              -name "*.lock"               -delete || true

