name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Coursier cache
      uses: coursier/cache-action@v5
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Run tests
      run:   sbt "test:testOnly ParserTests"
    - name: Build with SBT
      run: sbt 'set test in assembly := {}' assembly
    - name: Build docker
      uses: docker/build-push-action@v2
      with:
        load: true
        tags: verifier
        file: Dockerfile
