name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pull image
      run: docker pull simonthrane/uppaal_image:latest
    - name: Build and Test
      run:  docker run --rm -v $(pwd):/root simonthrane/uppaal_image /bin/bash -c 'cd /root && sbt clean test' 
